### ISSUE TITLE
Running an application in a java environment

### ISSUE THREAD

**Issue by mquisuisje** [Gcenx/macOS_Wine_builds#11]
Hello,
Thank you for the effort you make to run Windows applications on Mac.
I tried to install using your Wineskin Winery application with WS11WineCX64Bit19.0.1-1 as engine, a scientific program on Big Sur. The installation was done correctly but in order to function it needs Java JRE 1.6 which is included with the program in a sub-folder "jre1.6.0_05". The problem is that it cannot run javaw.exe which is in this subfolder. I have a message telling me that it cannot locate the virtual java machine. Any idea to solve this problem? Thank you

**Comment by Gcenx** [comment]
This isn’t something I’ve encountered before but as it’s unable to find the Java executable there’s two solutions I can think of.

- Installing a Java runtime into the wrapper/wineprefix using winetricks

- Adding the bundles Java into Windows PATH

Here’s an example from the mingw package
```
If you want your MinGW-generated windows binaries to work under wine out-of-the-box
        (and they are not statically linked), you can instruct wine
        to automatically search for dll-s by running:
            wine regedit
        Nagivate to:
            \[HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Environment\]
        or
            \[HKEY_CURRENT_USER\\Environment\]
        and add
            Z:[string map {/ \\} ${prefix}]\\${mingw_target}\\bin
        to the 'PATH' variable.

```
I’d assume doing something similar but using a Windows PATH like what’s already provided at that registry location would work

Avoid using Z: as that’s your mounted macOS file system aka “/“ meaning your wrapper won’t be movable anymore due to this hardcoded macOS PATH

**Comment by Gcenx** [comment]
Assuming this resolved your issue, reopen if needed
